apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.deployment.name }}-svc"
spec:
  type: NodePort
  ports:
  - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.port }}
  selector:
      app: {{ .Values.deployment.name }}
